const moveMap = {
    0: 'Swap',
    1: 'Tackle',
    2: 'Vine Whip',
    3: 'Growl',
    4: 'Razor Leaf',
    5: 'Solar Beam',
    6: 'Sleep Powder',
    7: 'Leech Seed',
    8: 'Scratch',
    9: 'Ember',
    10: 'Flamethrower',
    11: 'Smokescreen',
    12: 'Wing Attack',
    13: 'Dragon Claw',
    14: 'Water Gun',
    15: 'Tail Whip',
    16: 'Water Pulse',
    17: 'Bite',
    18: 'Hydro Pump',
    19: 'Skull Bash',
    20: 'String Shot',
    21: 'Harden',
    22: 'Gust',
    23: 'Confusion',
    24: 'Poison Sting',
    25: 'Twineedle',
    26: 'Poison Jab',
    27: 'Agility',
    28: 'Sand Attack',
    29: 'Hurricane',
    30: 'Hyper Fang',
    31: 'Crunch',
    32: 'Peck',
    33: 'Fury Attack',
    34: 'Drill Peck',
    35: 'Wrap',
    36: 'Glare',
    37: 'Thunderbolt',
    38: 'Charm',
    39: 'Bug Bite',
    40: 'Quick Attack',
    41: 'Giga Drain',
    42: 'Soft Boiled',
    43: 'Swords Dance',
    44: 'Drain Punch',
    45: 'Drain Kiss',
    46: 'Recover',
    47: 'Rest',
    48: 'Earthquake',
    49: 'Psychic',
    50: 'Ice Beam',
    51: 'Rock Slide',
    52: 'Shadow Ball',
    53: 'Iron Tail',
    54: 'Brick Break',
    55: 'Sludge Bomb',
    56: 'Thunder Wave',
    57: 'Toxic',
    58: 'Double Team',
    59: 'Focus Punch',
    60: 'Calm Mind',
    61: 'Blizzard',
    62: 'Leech Life',
    63: 'Earth Power',
    64: 'Aura Sphere',
    65: 'Thunder Punch',
    66: 'Will-O-Wisp',
    67: 'Air Slash',
    68: 'Shadow Claw',
    69: 'X-Scissor',
    70: 'Energy Ball',
    71: 'Flash Cannon',
    72: 'Heat Wave',
    73: 'Dark Pulse',
    74: 'Leaf Storm',
    75: 'Close Combat',
    76: 'Volt Switch',
    77: 'U-turn',
    78: 'Moonblast',
    79: 'Overheat',
    80: 'Inferno',
    81: 'Draco Meteor',
    82: 'Dragon Pulse',
    83: 'Dragon Dance',
    84: 'Flame Charge',
    85: 'Dragon Breath',
    86: 'Dragon Rage',
    87: 'Dragon Tail',
    88: 'Outrage',
    89: 'Fire Blast',
    90: 'Flare Blitz',
    91: 'Fire Spin',
    92: 'Flame Wheel',
    93: 'Flame Burst',
    94: 'Belly Drum',
    95: 'Brave Bird',
    96: 'Aerial Ace',
    97: 'Take Down',
    98: 'Double-Edge',
    99: 'Wild Charge',
    100: 'Volt Tackle',
    101: 'AccTest',
    102: 'multiTest',
    103: 'healTest'
};
